### ISSUE TITLE
Admin action to resend emails

### ISSUE THREAD

**Issue by sastred** [APSL/django-yubin#10]
Sometimes It is usefull to resend an email. It is easy from a Python shell:
```python
m = Message.objects.get(pk=3456)
qm = QueuedMessage(message=m)
qm.save()
```
but It would be nice to be able to do It from the admin with an admin action https://docs.djangoproject.com/en/1.9/ref/contrib/admin/actions/

**Comment by aaloy** [comment]
In the actual trunk. Added as a Django action
