### ISSUE TITLE
django-yubin don't work with Django 1.10

### ISSUE THREAD

**Issue by marctc** [APSL/django-yubin#11]
If you try to run any `manage.py` command (`runserver` for instance) Django crashes and dumps this error trace:

```
  File "/home/marc/virtualenvs/doploy/lib/python3.5/site-packages/django_yubin/admin.py", line 13, in <module>
    from django.conf.urls.defaults import *
ImportError: No module named 'django.conf.urls.defaults'
```

**Comment by sastred** [comment]
Django 1.10 removes lots of previously derecated features, I'm working on it.

https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10
