### ISSUE TITLE
Django-yubin 0.3.0

### ISSUE THREAD

**Issue by tomasgarzon** [APSL/django-yubin#13]
Hi, I'm trying to upgrade my django-yubin version to 0.3.0 and Django 1.10, but "pip install django-yubin" is working with 0.2.3 version (and pip install -e git+http://github.com/APSL/django-yubin.git#egg=django-yubin , too). I'm using Python 3.5. 
Thanks for your time.

**Comment by sastred** [comment]
Hi Tomas,

We are going to upload version 0.3.0 to PyPI in a few days. Meanwhile, I have create the tag 0.3.0 so you can use it with `pip install git+https://github.com/APSL/django-yubin@0.3.0`.

I will close this issue when 0.3.0 is in PyPI.

**Comment by sastred** [comment]
Hi @tomasgarzon,

Django Yubin 0.3.0 is now in PyPI, sorry for the delay.
