### ISSUE TITLE
Support for Django 1.11

### ISSUE THREAD

**Issue by batisteo** [APSL/django-yubin#23]
Django 1.10+ does not accept a `Context` any more, thus `autoescape off` might be needed in the templates.

For reference:
https://github.com/pinax/pinax-notifications/issues/68#issuecomment-258383323
https://github.com/pinax/pinax-notifications/pull/70/files

**Comment by sastred** [comment]
Hello @batisteo,

Thanks for the advice, I'm working on It now.
