### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by the-mace** [APSL/django-yubin#24]
I've been using django-yubin for a while and it's a great addition. My challenge is sometimes my queue gets too many items in it and then I have a large amount of emails to send (all opt-in, no spamming). My email provider doesn't like it when the volume spikes and starts aggressively throttling and can even lock the account for a while. It would be really helpful if django-yubin had some way of limiting the number of emails per time period. So feed from the queue but if we've sent X emails in this cron cycle then stop sending emails until next cycle.

Is anything like this possible now or is it possible to add something like this?

I found an option, block_size, in the code which I didn't see in the docs. It's related but still sends all mail in the queue.

**Comment by sastred** [comment]
Hello @the-mace,

That's a nice to have feature. We are interested in this feature but we are currently quite busy so I can't tell you when it will be developed. Meanwhile, pull request are wellcome.

**Comment by the-mace** [comment]
I actually implemented it for myself on my fork. I'll send it your way and you can see if you want it. It got me past my backlog of emails.

**Comment by sastred** [comment]
Resolved in #25
