### ISSUE TITLE
New 1.0.0 version doesn't work in django < 2.0

### ISSUE THREAD

**Issue by jdruiter** [APSL/django-yubin#34]
File "C:\evalite\evaliteCO\ENV\lib\site-packages\django_yubin\admin.py", line 7, in <module>
    from django.urls import reverse
ImportError: No module named urls

Worked fine with versions 0.7 and below.

**Comment by sastred** [comment]
Hi @jdruiter,

What version of Django are you using? django-yubin 1.0.0 supports Django 1.10+ (https://github.com/APSL/django-yubin/blob/master/setup.py#L56) and the `reverse` import exists in Django 1.10+:

https://github.com/django/django/blob/1.10.8/django/urls/__init__.py#L18
https://github.com/django/django/blob/1.11.9/django/urls/__init__.py#L18
https://github.com/django/django/blob/2.0.1/django/urls/__init__.py#L21

**Comment by jdruiter** [comment]
1.9.9

Upgrading django to 1.10 fixed the issue.
