### ISSUE TITLE
To support creating a single Email object with several addresses

### ISSUE THREAD

**Issue by celdrake** [APSL/django-yubin#36]
It would be nice to support multiple addresses (either with to / cc / bcc fields) for the same Email.
Currently, a new Message object is created per address. 

By allowing the same email to be sent to multiple addresses, we could reduce table space significantly.

**Comment by sastred** [comment]
Fixed in https://github.com/APSL/django-yubin/commit/798c0cc522e765bf3aa502f68c82e4da149b1e0b

https://github.com/APSL/django-yubin/releases/tag/2.0.0b3
https://pypi.org/project/django-yubin/2.0.0b3/
