### ISSUE TITLE
Lock already in place. Exiting.

### ISSUE THREAD

**Issue by drownload** [APSL/django-yubin#44]
Im having a significant issue with the lock system. 

Usually yubin works great for everything. However, sometimes the lock file does not get deleted properly when the program exits. I dont know if its because of abnormal termination or due to some other reason. 

Whatever the cause - after that, yubin cant run anymore because it sees the old lock file. Since Im not getting emails, sometimes it takes me days or weeks to realize that there is a problem. This happens rarely but often enough - roughly every few months.

Obviously this is a really serious issue on a production system.

I see there is a finally: block where the lock is supposed to get released. I have no idea why its not getting there sometimes. 

Im not so familiar with the system, so the only solution I can think of is to create a management command that can be run say once or twice a day that checks for a really old lock file and deletes it. For instance a lock file thats 4 hours old is probably not really supposed to be there.

Maybe there is a more elegant and correct solution but thats all I can come up with given my limited knowledge

Thanks

Daniel

**Comment by sastred** [comment]
Hello @drownload ,

Your are right, we have suffered the same issue and we still don't now why this happen, the `finally` clause should release the lock but mysteriously it does not.

Currently there are to ways to handle this problem:

1. In the [latest release](https://github.com/APSL/django-yubin/releases/tag/1.2.0) we have added a [healthcheck view](https://github.com/APSL/django-yubin/blob/master/django_yubin/views.py#L9) that can be used by an external monitoring tool (for example, Nagios or Check_MK) to check if there is a problem with sending emails.

2. Running a cron job that check if the lock file creation date is too old an delete the file.

Sorry for the inconvenience, we will fix the error as soon as we know how to solve it.

Best regards,
Dani

**Comment by drownload** [comment]
Hi Dani

Thanks for your response.

Id like to do option #2 it sounds much simpler. Im not that great with bash scripts unf. Do you have a sample script that you could send me?

Also - might be a good idea to turn #2 into a management command built right into yubin

Thanks so much

Daniel

**Comment by sastred** [comment]
Hi Daniel,

I can't help you with option 2, we are using option 1.

If you try to develop option 2 all pull requests are welcome : )

Best regards,
Dani

**Comment by sastred** [comment]
No news in 11 months, closing PR.
