### ISSUE TITLE
No CI for pushes/pull requests (Travis)

### ISSUE THREAD

**Issue by sergei-maertens** [APSL/django-yubin#7]
I see that there is no Travis integration. I could add this (set up the whole `tox` stack) so you can at least see if the build is failing for certain Python/Django versions or not.

What's the support policy? Which Python/Django versions? I'd suggest Py27, Py34 and Py35, Django 1.8 and Django 1.9. For the rest I would point to django-mailer-2, which is unsupported but so are the Python/Django versions lower than those specified.

**Comment by aaloy** [comment]
Hi Sergei, 

It could be nice. We've planned to add Travis integration but not enough time to do it, so you're well come to contribute.

I agre with you in the support policy. I'm going to update documentation and add a Django/Python version support.

**Comment by sergei-maertens** [comment]
Cool, I'll see if I can make some time available in the next few weeks.

**Comment by sergei-maertens** [comment]
I've added PR #8

**Comment by sergei-maertens** [comment]
PR is merged, so this is no longer relevant :-)
