### ISSUE TITLE
Unicode e-mail address + Py3

### ISSUE THREAD

**Issue by sergei-maertens** [APSL/django-yubin#9]
Something I ran into when working on the test-suite: unicode e-mail addresses where the address itself is unicode is not possible on Py3. I believe this to be something Django/Python itself should handle, and submitted issues to both of them:

https://code.djangoproject.com/ticket/25986 and http://bugs.python.org/issue25955

Currently the unicode e-mail address test is skipped, but it's probably worth a mention in the docs that unicode e-mail addresses are problematic. I think however, that Django itself won't let you enter a unicode EmailField on Py3.

**Comment by sergei-maertens** [comment]
heads-up: the unicode issue fix has been merged in Django master: https://github.com/django/django/commit/ec009ef1d8470f8fdb32802339fe2615e35887a1, so the mentioned test should be skipped only on Django < 1.10

**Comment by sastred** [comment]
Fixed in PR #12
